### ISSUE TITLE
ValueError: could not convert string to float: X

### ISSUE THREAD

**Issue by stanedav** [WGLab/InterVar#3]
Hello, I am trying to run your tool with this command:
./InterVar.py  -b hg19 --table_annovar='/annovar/table_annovar.pl' --convert2annovar='/annovar/convert2annovar.pl' --annotate_variation='/annovar/annotate_variation.pl' -i '/vcf_wes/sample.vcf' --input_type=VCF  -o '/vcf_wes/sample_output'

After few moment I am getting this error:
``
NOTICE: Multianno output file is written to /home/lab/galaxy-Win-Lin/David/vcf_wes/6788_output.hg19_multianno.txt
Notice: Begin the variants interpretation by InterVar 

Traceback (most recent call last):
 
 File "./InterVar.py", line 2022, in <module>
    main()

  File "./InterVar.py", line 1996, in main
    sum2=my_inter_var(annovar_outfile)

  File "./InterVar.py", line 1771, in my_inter_var
    intervar_bp=assign(BP,line,Freqs_flgs,Funcanno_flgs,Allels_flgs)

  File "./InterVar.py", line 1599, in assign
    PM2=check_PM2(line,Freqs_flgs,Allels_flgs,Funcanno_flgs,mim2gene_dict,mim2gene_dict2)

  File "./InterVar.py", line 1055, in check_PM2
    if(cls[Freqs_flgs[key]]!='.' and float(cls[Freqs_flgs[key]])>=cutoff_maf): 
ValueError: could not convert string to float: X
``

In attachment you can see few lines of my vcf,
[error_intervar.txt](https://github.com/WGLab/InterVar/files/810484/error_intervar.txt)

Can you help? Thank you in advancei

**Comment by quanliustc** [comment]
I tested your provided vcf,it  is no prolem.

Please show your  version of  python,  config,ini and full output of the screen.

Also make sure  all the files  you using are updated.

 

Best,

Quan LI

leequan@gmail.com

**Comment by quanliustc** [comment]
please update the intervar. The value error has been fixed for this issue.

**Comment by stanedav** [comment]
Hello, thank you for quick response, I updated annovar and intervar and
everything works fine!

Thank you very much

David Stanek

2017-03-01 14:22 GMT+01:00 Quan LI <notifications@github.com>:

**Comment by yinbinqiu** [comment]
Hello, I am using intervar (2021-8-update), annovar (Version: $Date: 2020-06-07), but the above error still occurs, how can I solve it?

**Comment by WhiteKnightZMA** [comment]
> please update the intervar. The value error has been fixed for this issue.

Hello, I have the same error with the latest Intervar version. 


Notice: Begin the variants interpretation by InterVar
Traceback (most recent call last):
  File "./Intervar.py", line 2126, in <module>
    main()
  File "./Intervar.py", line 2095, in main
    sum2=my_inter_var(annovar_outfile)
  File "./Intervar.py", line 1844, in my_inter_var
    intervar_bp=assign(BP,line,Freqs_flgs,Funcanno_flgs,Allels_flgs)
  File "./Intervar.py", line 1715, in assign
    BP7=check_BP7(line,Funcanno_flgs,Allels_flgs)
  File "./Intervar.py", line 1627, in check_BP7
    if float(cls[Funcanno_flgs['dbscSNV_RF_SCORE']])<0.6 and float(cls[Funcanno_flgs['dbscSNV_ADA_SCORE']])<0.6:
ValueError: could not convert string to float: X
